name: Build

on:
  push:
    branches:
      - main
      - dev
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main
      - dev
      - "releases/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: config kube namespace
        run: kubectl config set-context --current --namespace=default
      - name: Execute Gradle build
        run: ./gradlew clean :test:build -Pno-pandoc
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'